language: swift
osx_image: xcode11.3

cache: bundler

jobs:
  include:
  - stage: build
    name: "Building iOS"
    script: bundle exec fastlane build_framework platform:'iOS'

  - stage: build
    name: "Building tvOS"
    script: bundle exec fastlane build_framework platform:'tvOS'

  - stage: build
    name: "Building example app"
    script: bundle exec fastlane build_example_app ios_version:'13.2'

  - stage: test
    name: "Running example app UI tests suite"
    script: bundle exec fastlane run_uiTests device:'iPhone 8'

  - stage: deploy_pod
    name: "Deploying pod to Trunk"
    script: bundle exec fastlane deploy_pod

stages:
- name: build
  if: (type = pull_request OR type = push) AND branch = master

- name: test
  if: (type = pull_request OR type = push) AND branch = master

- name: deploy_pod
  if: type = push AND tag IS present
